[package]
name = "auto-battler-core"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wasm-bindgen = "0.2.79"

[dependencies.serde]
version = "1.0.126"
default-features = false
features = ["derive"]

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-12'
version = '4.0.0-dev'

[features]
default = ['std']

std = [
    "serde/std",
    "sp-std/std"
    ]